"""
Ghost Hub SDK 组件模块 - 自包含实现
"""

from .intention_bank import (
    IntentionBankComponent,
    IntentVector,
    Template,
    Task,
    IntentMatch,
    MatchResult,
    IntentParser,
    IntentMatcher,
    TemplateLoader,
    SemanticSimilarity,
    TaskGraphBuilder,
)
from .no_ui_adapter import (
    NoUIAdapterComponent,
    Device,
    DeviceCommand,
    CommandResult,
    BatchCommandResult,
    Scene,
    DeviceType,
    DeviceProtocol,
    IntentCommandEngine,
    HTTPAdapter,
    MQTTAdapter,
    WebSocketAdapter,
    SceneManager,
)
from .agent_federation import (
    AgentFederationComponent,
    Agent,
    Message,
    Session,
    IntentRoute,
    Task as FedTask,
    TaskDistributionResult,
    AggregatedResult,
    AgentStatus,
    MessageType,
    RoutingStrategy,
    ServiceRegistry,
    Router,
    MessageProtocol,
    TaskDistributor,
    ResultAggregator,
)

__all__ = [
    # Components
    "IntentionBankComponent",
    "NoUIAdapterComponent",
    "AgentFederationComponent",
    # Intention Bank
    "IntentVector",
    "Template",
    "Task",
    "IntentMatch",
    "MatchResult",
    "IntentParser",
    "IntentMatcher",
    "TemplateLoader",
    "SemanticSimilarity",
    "TaskGraphBuilder",
    # NoUI Adapter
    "Device",
    "DeviceCommand",
    "CommandResult",
    "BatchCommandResult",
    "Scene",
    "DeviceType",
    "DeviceProtocol",
    "IntentCommandEngine",
    "HTTPAdapter",
    "MQTTAdapter",
    "WebSocketAdapter",
    "SceneManager",
    # Agent Federation
    "Agent",
    "Message",
    "Session",
    "FedTask",
    "TaskDistributionResult",
    "AggregatedResult",
    "AgentStatus",
    "MessageType",
    "RoutingStrategy",
    "IntentRoute",
    "ServiceRegistry",
    "Router",
    "MessageProtocol",
    "TaskDistributor",
    "ResultAggregator",
]
